import 'dart:io';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:speakwise/design/tokens/app_colors.dart';

/// Verifies PRD R7.1.3: every token pair MUST pass WCAG AA — 4.5:1 for body
/// text, 3:1 for large text and UI boundaries — in BOTH modes, "verified
/// programmatically", with the contrast table committed to `/qa/`.
///
/// This test is the verification, and it writes the table as a side effect so
/// the two can never drift apart. Change a token and either this goes red or
/// the committed table updates.
void main() {
  final rows = <_Row>[];

  group('WCAG AA contrast (PRD R7.1.3)', () {
    for (final entry in {'dark': AppColors.dark, 'light': AppColors.light}.entries) {
      final mode = entry.key;
      final c = entry.value;

      // Body text must clear 4.5:1.
      for (final pair in <_Pair>[
        _Pair('ink on bg', c.ink, c.bg),
        _Pair('ink on surface', c.ink, c.surface),
        _Pair('ink on surfaceRaised', c.ink, c.surfaceRaised),
        _Pair('muted on bg', c.muted, c.bg),
        _Pair('muted on surface', c.muted, c.surface),
        _Pair('muted on surfaceRaised', c.muted, c.surfaceRaised),
      ]) {
        test('$mode: ${pair.name} >= 4.5:1 (body)', () {
          final ratio = _contrast(pair.fg, pair.bg);
          rows.add(_Row(mode, pair.name, ratio, 4.5, 'body text'));
          expect(
            ratio,
            greaterThanOrEqualTo(4.5),
            reason:
                '$mode ${pair.name} is ${ratio.toStringAsFixed(2)}:1, '
                'below the 4.5:1 body-text floor',
          );
        });
      }

      // Accents and UI boundaries must clear 3:1.
      for (final pair in <_Pair>[
        _Pair('signal on bg', c.signal, c.bg),
        _Pair('signal on surface', c.signal, c.surface),
        _Pair('live on bg', c.live, c.bg),
        _Pair('live on surface', c.live, c.surface),
        _Pair('good on bg', c.good, c.bg),
        _Pair('good on surface', c.good, c.surface),
      ]) {
        test('$mode: ${pair.name} >= 3:1 (large / UI)', () {
          final ratio = _contrast(pair.fg, pair.bg);
          rows.add(_Row(mode, pair.name, ratio, 3.0, 'large text / UI'));
          expect(
            ratio,
            greaterThanOrEqualTo(3.0),
            reason:
                '$mode ${pair.name} is ${ratio.toStringAsFixed(2)}:1, '
                'below the 3:1 large-text and UI-boundary floor',
          );
        });
      }
    }

    test('live red is distinguishable from signal amber', () {
      // R7.1.1 is diegetic: a user must be able to tell from across the room
      // whether the microphone is hot. If these two ever converge, that
      // affordance is gone even though every individual pair still passes.
      //
      // NOTE ON THE METRIC. This deliberately does NOT use WCAG contrast.
      // Contrast ratio is a luminance measure, and two colours can be equally
      // bright yet obviously different — red and green being the standard
      // example. In light mode signal (#8A5A00) and live (#D62B1F) sit at
      // 1.19:1 contrast, which sounds alarming and is not: they differ almost
      // entirely in hue. The first version of this test asserted on contrast
      // and failed the palette for it. The palette was right; the test was
      // measuring the wrong property.
      //
      // CIE76 ΔE in Lab space is the appropriate measure. ΔE above ~25 reads
      // as a clearly different colour rather than a shade of the same one.
      for (final entry
          in {'dark': AppColors.dark, 'light': AppColors.light}.entries) {
        final c = entry.value;
        final delta = _deltaE(c.signal, c.live);
        rows.add(_Row(entry.key, 'signal vs live (ΔE)', delta, 25, 'diegetic'));
        expect(
          delta,
          greaterThan(25),
          reason:
              '${entry.key}: signal and live are perceptually too close '
              '(ΔE ${delta.toStringAsFixed(1)}) to tell apart at a glance',
        );
      }
    });
  });

  tearDownAll(() {
    if (rows.isEmpty) return;
    final buffer = StringBuffer()
      ..writeln('# Contrast table')
      ..writeln()
      ..writeln('Generated by `test/design/contrast_test.dart`. Do not edit by')
      ..writeln('hand — re-run `flutter test` instead.')
      ..writeln()
      ..writeln('Evidence for PRD R7.1.3 (WCAG AA in both modes).')
      ..writeln()
      ..writeln('| Mode | Pair | Ratio | Floor | Applies to | Pass |')
      ..writeln('|---|---|---|---|---|---|');

    rows.sort((a, b) {
      final byMode = a.mode.compareTo(b.mode);
      return byMode != 0 ? byMode : a.name.compareTo(b.name);
    });
    for (final r in rows) {
      buffer.writeln(
        '| ${r.mode} | ${r.name} | ${r.ratio.toStringAsFixed(2)}:1 '
        '| ${r.floor.toStringAsFixed(1)}:1 | ${r.applies} '
        '| ${r.ratio >= r.floor ? 'PASS' : 'FAIL'} |',
      );
    }

    Directory('qa').createSync(recursive: true);
    File('qa/contrast-table.md').writeAsStringSync(buffer.toString());
  });
}

class _Pair {
  const _Pair(this.name, this.fg, this.bg);
  final String name;
  final Color fg;
  final Color bg;
}

class _Row {
  const _Row(this.mode, this.name, this.ratio, this.floor, this.applies);
  final String mode;
  final String name;
  final double ratio;
  final double floor;
  final String applies;
}

/// WCAG 2.1 relative luminance.
double _luminance(Color c) {
  double channel(double v) =>
      v <= 0.03928 ? v / 12.92 : math.pow((v + 0.055) / 1.055, 2.4).toDouble();
  return 0.2126 * channel(c.r) + 0.7152 * channel(c.g) + 0.0722 * channel(c.b);
}

/// WCAG 2.1 contrast ratio, always >= 1.0 and order-independent.
double _contrast(Color a, Color b) {
  final la = _luminance(a);
  final lb = _luminance(b);
  final lighter = math.max(la, lb);
  final darker = math.min(la, lb);
  return (lighter + 0.05) / (darker + 0.05);
}

/// sRGB → CIE L*a*b* (D65 white point).
({double l, double a, double b}) _lab(Color c) {
  double lin(double v) =>
      v <= 0.04045 ? v / 12.92 : math.pow((v + 0.055) / 1.055, 2.4).toDouble();

  final r = lin(c.r);
  final g = lin(c.g);
  final bl = lin(c.b);

  // Linear sRGB → XYZ.
  final x = (0.4124 * r + 0.3576 * g + 0.1805 * bl) / 0.95047;
  final y = (0.2126 * r + 0.7152 * g + 0.0722 * bl) / 1.00000;
  final z = (0.0193 * r + 0.1192 * g + 0.9505 * bl) / 1.08883;

  double f(double t) => t > 0.008856
      ? math.pow(t, 1 / 3).toDouble()
      : (7.787 * t) + (16 / 116);

  final fx = f(x);
  final fy = f(y);
  final fz = f(z);

  return (l: 116 * fy - 16, a: 500 * (fx - fy), b: 200 * (fy - fz));
}

/// CIE76 perceptual colour difference. Roughly: <2 is imperceptible, ~10 is a
/// noticeable shade change, >25 reads as a different colour entirely.
double _deltaE(Color x, Color y) {
  final a = _lab(x);
  final b = _lab(y);
  final dl = a.l - b.l;
  final da = a.a - b.a;
  final db = a.b - b.b;
  return math.sqrt(dl * dl + da * da + db * db);
}
