import 'dart:io';

import '../support/dart_source.dart';

/// Rewrites `test/l10n_baseline.txt` from the current state of `lib/`.
///
/// ```
/// dart run test/tool/update_l10n_baseline.dart
/// ```
///
/// Run this **after** extracting strings out of a file, never to make a
/// failing test pass. The difference matters: `l10n_test.dart` fails both when
/// a file gains copy and when it loses copy without the baseline following, and
/// only the second of those is what this tool is for. Using it on the first is
/// how a ratchet becomes a rubber stamp.
///
/// The old and new totals are printed so the direction of travel is visible in
/// the terminal and in the commit message.
void main() {
  final previous = readL10nBaseline();

  final counts = <String, int>{};
  for (final literal in hardcodedUserFacingStrings()) {
    counts[literal.path] = (counts[literal.path] ?? 0) + 1;
  }

  final paths = counts.keys.toList()..sort();
  final total = counts.values.fold(0, (a, b) => a + b);
  final previousTotal = previous.values.fold(0, (a, b) => a + b);

  final buffer = StringBuffer()
    ..writeln('# R11.7 ratchet — hardcoded user-facing strings still in lib/.')
    ..writeln('#')
    ..writeln('# Generated by test/tool/update_l10n_baseline.dart and enforced')
    ..writeln('# by test/l10n_test.dart. A file absent from this list must')
    ..writeln('# have zero, which is what makes every new file localized from')
    ..writeln('# birth. These counts may only go down.')
    ..writeln('#')
    ..writeln('# Total: $total in ${paths.length} files.')
    ..writeln('#')
    ..writeln('# Nearly all of it is the pre-rebuild app. PRD §15 deletes')
    ..writeln('# these files milestone by milestone, so the honest way to')
    ..writeln('# empty this list is to finish the rebuild, not to translate')
    ..writeln('# copy that §7.6 is about to rewrite.')
    ..writeln();

  for (final path in paths) {
    buffer.writeln('${path.padRight(60)} ${counts[path]}');
  }

  File(l10nBaselinePath).writeAsStringSync(buffer.toString());

  stdout.writeln('Wrote $l10nBaselinePath');
  stdout.writeln('  files:  ${previous.length} -> ${paths.length}');
  stdout.writeln('  strings: $previousTotal -> $total');
  if (total > previousTotal) {
    stdout.writeln(
      '\n  WARNING: the count went UP. This tool is for recording extraction,\n'
      '  not for absorbing new hardcoded copy. Check the diff before you\n'
      '  commit it.',
    );
  }
}
