-- R4.1.3's example opening line, as data — PRD §5.3.2.
--
-- R4.1.3: "Selecting a partner opens a short brief screen: what this partner
-- does, **an example opening line**, and an optional one-line goal."
--
-- Milestone 4 shipped that screen with the opening line derived from
-- `description`, so the brief showed the same sentence twice — once as the
-- partner's summary and once under the heading "How it opens". Found by
-- looking at it on a phone; it reads as a bug, because it is one.
--
-- ## Why a column rather than a constant in the client
--
-- §5.3.2: "Built-in partners ship as data, not code, so they can be edited
-- without a release." An opening line hardcoded in Dart would go stale the
-- first time somebody edited a `system_prompt` here, and the mismatch would be
-- invisible — the brief would promise one thing and the partner would do
-- another.
--
-- ## Why it is not generated by the model
--
-- It is decoration on a screen the user sees before any quota is spent, and
-- RESEARCH.md §4.A puts the free-tier breach point at 8-48 daily active users.
-- Spending a model call per brief screen to write a sentence that changes
-- never is the wrong place for scarce quota — the same argument `deriveTitle`
-- makes in the gateway contract.
--
-- It is also a *sample*, not a promise. The real first turn comes from the
-- model and will differ; the UI labels it "How it opens" rather than quoting it
-- as what will be said.

alter table public.partners
  add column opening_line text;

comment on column public.partners.opening_line is
  'R4.1.3''s example opening line, shown on the brief screen. Readable by '
  'clients, unlike system_prompt — it is written FOR the user to read.';

update public.partners set opening_line = case id
  when '11111111-1111-4111-8111-000000000001' then
    'What is on your mind today?'
  when '11111111-1111-4111-8111-000000000002' then
    'Thanks for coming in. To start, tell me about yourself.'
  when '11111111-1111-4111-8111-000000000003' then
    'Hello. What did you do today?'
  when '11111111-1111-4111-8111-000000000004' then
    'Whenever you are ready, take it from the top. I will not interrupt.'
  when '11111111-1111-4111-8111-000000000005' then
    'Pick a position and state it. I will take the other side.'
  else opening_line
end
where is_builtin;
